### ISSUE TITLE
Input contains NaN on multiprocessing/pool.py

### ISSUE THREAD

**Issue by LoveenDyall** [intive-DataScience/tbats#8] opened 2019-08-05 16:04 UTC
File "../forecasters/statsforecasters.py", line 78, in search
model_fit = model.fit(train)
File "../.local/lib/python3.5/site-packages/tbats/abstract/Estimator.py", line 97, in fit
best_model = self._do_fit(y)
File "../.local/lib/python3.5/site-packages/tbats/tbats/TBATS.py", line 76, in _do_fit
seasonal_model = self._choose_model_from_possible_component_settings(y, components_grid=components_grid)
File "../.local/lib/python3.5/site-packages/tbats/abstract/Estimator.py", line 143, in _choose_model_from_possible_component_settings
models = pool.map(self._case_fit, components_grid)
File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
return self._map_async(func, iterable, mapstar, chunksize).get()
File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
raise self._value
ValueError: Input contains NaN, infinity or a value too large for dtype('float64')

Hi I also keep getting this error, I have verified my training data does not contain any NaN or infinite values using: 
`if np.isfinite(train).all():`

also i'm determining seasonal_periods using pacf from statsmodels python package, and picking out the lag with highest confidence coefficient

**Comment by cotterpl** [comment] 2019-08-06 08:07
Can you try turning box cox off using use_box_cox=False? Does it solve the problem?

**Comment by cotterpl** [comment] 2020-02-03 13:46
Closing as I am unable to reproduce this and there has been no feedback on this for a few months.

**Closed by cotterpl** 2020-02-03 13:46 UTC
